### ISSUE TITLE
PyCon US 2022

### ISSUE THREAD

**Issue by treyhunner** [pyvideo/data#1126] opened 2023-06-02 18:02 UTC
- Schedule: https://us.pycon.org/2022/schedule/
- Playlist: https://www.youtube.com/playlist?list=PL2Uw4_HvXqvYeXy8ab7iRHjA-9HiYhRQl

Steps this will require, as far as I can tell from the [contributing guidelines](https://github.com/pyvideo/data/blob/eb62953a46144a7814a63eee7fe7812b974c46aa/CONTRIBUTING.rst#adding-data) are:

1. Use [pyvideo_scrape](https://github.com/pyvideo/pyvideo_scrape) to scrape data from the YouTube playlist
2. Use [pyvideo_lektor](https://github.com/pyvideo/pyvideo_lektor) to update missing fields in the data
3. Open [a pull request](https://github.com/pyvideo/data/blob/eb62953a46144a7814a63eee7fe7812b974c46aa/CONTRIBUTING.rst#pull-request)

CC-ing @di, who contributed the 2021 videos and who might be able to correct me if the process above isn't quite right.

**Comment by ewdurbin** [comment] 2023-06-02 18:14
`https://us.pycon.org/2022/schedule/conference.json` might be helpful :)

**Comment by theonlypat** [comment] 2023-06-06 15:28
I just submitted a PR for the 2022 videos. For reference: #1128

**Comment by jonafato** [comment] 2023-06-07 00:19
> `https://us.pycon.org/2022/schedule/conference.json` might be helpful :)

It looks like the JSON document was not included in the 2022 site archive, but it does exist for 2023. (Not a big deal for this purpose, mostly pointing that out in case it was intended to be and easy to backfill.)

**Comment by jonafato** [comment] 2023-06-08 19:20
Fixed by #1128.

**Closed by jonafato** 2023-06-08 19:20 UTC
