### ISSUE TITLE
North Bay Python 2017

### ISSUE THREAD

**Issue by redapple** [pyvideo/data#637] opened 2018-11-09 10:32 UTC
* YouTube: https://www.youtube.com/playlist?list=PLaeNpBNgqQWvWl273wwS3f-iEgDWNuoxN
* Website: https://2017.northbaypython.org/
* Schedule: https://2017.northbaypython.org/schedule/

**Comment by Daniel-at-github** [comment] 2018-11-10 10:35
~~~ yml
- title: North Bay Python 2017
  dir: north-bay-python-2017
  youtube_list:
    - https://www.youtube.com/playlist?list=PLaeNpBNgqQWvWl273wwS3f-iEgDWNuoxN
  related_urls:
  - label: Group web
    url: https://2017.northbaypython.org/
  - label: Group meeting schedule
    url: https://2017.northbaypython.org/schedule/
  language: eng
  issue: 637
  minimal_download: true
  tags:
~~~

**Comment by Daniel-at-github** [comment] 2018-11-10 10:46
Duplicate of #430

**Closed by Daniel-at-github** 2018-11-10 10:46 UTC
Labels: event::group, minimal_download
